aws-samples/mistral-on-aws

notebooks/mistral_usecases.ipynb

modify function calling description
clear all cell output

function calling description

---

Transition_from_openai_to_mistral.ipynb
notebooks/Transition_from_openai_to_mistral.ipynb

Transitioning from OpenAi to Mistral

---

notebooks/Mistral_model_RAG_pipeline_evaluation.ipynb

Update notebook title from “Mistral Models RAG Pipeline Evaluation with LlamaIndex and Ragas” to “Advanced RAG Pipeline for Mistral Models with Q&A Automation and Model Evaluation using LlamaIndex and Ragas”

Update notebook title

---

notebooks/Tool_Use_with_Mistral.ipynb

Adding new introductory notebook for tool use with the converse api and Mistral Large

Tool Use with Mistral

---

.github/workflows/docs.yml

change github page build trigger

---

notebooks/mistral_usecases.ipynb

update mistral_usecases.ipynb with native function calling

---

notebooks/Tool_Use_with_Mistral.ipynb

Updated notebook to include reference to mistral small

---

notebooks/Codestral-DeepSpeed-SageMaker.ipynb

Codestral deployment on Amazon SageMaker with DeepSpeed

Codestral deployment with DeepSpeed

---

notebooks/Mistral_model_RAG_pipeline_evaluation.ipynb

Fixing typos in the notebook documentation.

Fixing typos in the Mistral_model_RAG_pipeline_evaluation.ipynb file

---

notebooks/distributed-inference-deployment/Mixtral-8x7b-TensorRT-LLM-SageMaker.ipynb
notebooks/distributed-inference-deployment/Mixtral-8x7b-vLLM-SageMaker.ipynb

Notebooks for distributed inference on SageMaker

distributed inference on sagemaker

---

notebooks/Large_2_Release_Highlights.ipynb

*Issue #, if available:* N/A
*Description of changes:* Fix Typo

Fix typo on notebook

---

notebooks/mixtral-8x7b-qlora-finetune.ipynb

This example notebook demonstrates running a fine-tuning job on the Mixtral 8x7B model with the QLoRA and bitsandbytes packages. This is run sing SageMaker Studio Notebooks (or alternatively, it can be run on a simple SageMaker Notebook) on accelerated instances (GPUs) - this example uses a single g5.48xlarge (A10G) instance.

Adding QLoRA Mixtral 8x7B Finetuning notebook

---

notebooks/Tool_Use_with_Mistral.ipynb

Added Large 2 and updated ToolChoice section

---

notebooks/Large_2_Release_Highlights.ipynb

Large 2 highlights update

---

notebooks/Language_Comparison_Large_1_2.ipynb

New notebook comparing language capabilities of Large 1 & 2

---

notebooks/mixtral_finetune_qlora_sft/finetune-mixtral.ipynb
notebooks/mixtral_finetune_qlora_sft/scripts/launch_fsdp_qlora.py
notebooks/mixtral_finetune_qlora_sft/scripts/merge_model_adapter.py
notebooks/mixtral_finetune_qlora_sft/scripts/requirements.txt

Adding Mixtral SFT QLoRA FT sample

Adding Mixtral SFT QLoRA FT sample

---

notebooks/mixtral_finetune_qlora_sft/finetune-mixtral.ipynb

Changing key

---

notebooks/Mistral_Large_2_JSON_Mode.ipynb

Description of changes:
Add example implementation of JSON Mode using Mistral Large-2 model 

JSON Mode Dive Deep

---

notebooks/Mistral_Large_2_JSON_Mode.ipynb

clean notebook

---

notebooks/Pixtral-samples/Pixtral-12b-LMI-SageMaker-realtime-inference.ipynb

Deploys Pixtral 12b on LMI container usign DJLServing framework version 0.30.0 on SageMaker endpoint for real-time inference.

Pixtral 12b LMI DJLServing v0.30.0 on SageMaker realtime inference

---

notebooks/Pixtral-samples/Pixtral-12b-Performance-Benchmarking.ipynb

Added notebook to benchmark Pixtral12b in a variety of instance types

Added notebook to benchmark Pixtral12b in a variety of instance types

---

.gitignore

Adding code snippet to generate generate SQL from Entity Relationship a Diagram.

Generate SQL from ER Diagram

---

README.md

Restructure

---

Mistral Large 2/ReAct_LlamaIndex_Large 2.py

updated notebook

---

MCP/MCP_Mistral_app_demo/gradio_app.py
MCP/MCP_Mistral_app_demo/src/agent.py

This PR implements a new feature allowing users to upload images directly to our Gradio application.
- A new field is added in the Gradio UI to upload images
- `invoke_with_prompt()` function in `src/agent.py` is updated to support: text, image url, image
Response:

Add feature to upload image to Gradio app

---

Mistral OCR/Mistral-OCR-SageMaker-Deployment-example.ipynb

Added Mistral OCR deployment on SageMaker example

---

MCP/MCP_Mistral_app_demo_with_Strands/README.md
MCP/MCP_Mistral_app_demo_with_Strands/chat.py
MCP/MCP_Mistral_app_demo_with_Strands/config.py
MCP/MCP_Mistral_app_demo_with_Strands/gradio_app.py
MCP/MCP_Mistral_app_demo_with_Strands/requirements.txt
MCP/MCP_Mistral_app_demo_with_Strands/server_configs.py

Added MCP demo with Strands and mistral models

---

MCP/MCP_Mistral_app_demo/src/chat.py

Replaces custom `BedrockConverseAgent` implementation with the `Strands` framework for better maintainability and standardization.

Update the chat application to Strands
